# Generated by Django 2.1.7 on 2019-03-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='img',
            field=models.ImageField(default='pages/advertises/coming_soon.png', upload_to='pages/advertises'),
        ),
    ]
