# Generated by Django 2.1.7 on 2019-03-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190301_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='img',
            field=models.ImageField(upload_to='pages/advertises'),
        ),
    ]
