# Generated by Django 2.1.7 on 2019-03-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='accessories/no.png', upload_to='accessories/')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('title', models.CharField(max_length=50)),
                ('overview', models.TextField(blank=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
