# Generated by Django 2.1.7 on 2019-03-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_auto_20190307_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='category',
            field=models.CharField(choices=[('Bookmarks', 'Bookmarks'), ('Book covers', 'Book covers'), ('Bookend', 'Bookend'), ('Book stands', 'Book stands'), ('Book light', 'Book light'), ('Notebooks', 'Notebooks')], default='Bookmarks', max_length=50),
        ),
    ]
