# Generated by Django 2.1.7 on 2019-02-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190224_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='classification',
            field=models.CharField(choices=[('Art & Design', 'Art & Design'), ('Biographies', 'Biographies'), ('Business', 'Business'), ('Children', 'Children'), ('Cooking & Nutrition', 'Cooking & Nutrition'), ('Crafts & Hobbies', 'Crafts & Hobbies'), ('Egypt', 'Egypt'), ('History & Politics', 'History & Politics'), ('Literature & Fiction', 'Literature & Fiction'), ('Mind & Body', 'Mind & Body'), ('Reference', 'Reference'), ('Religion', 'Religion'), ('Society', 'Society'), ('Sports', 'Sports'), ('Teens', 'Teens'), ('Travel', 'Travel')], default='Art & Design', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
