# Generated by Django 2.1.7 on 2019-03-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190303_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_best_selling',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_new_released',
            field=models.BooleanField(),
        ),
    ]
