# Generated by Django 2.1.7 on 2019-03-05 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190305_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_new_released',
        ),
        migrations.AddField(
            model_name='book',
            name='book_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
